Repository Step3-kakao-tech-campus/Team17_BE, pull requests merged in 2023-11, with the labels that each got.

#130 리뷰 작성 기능
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/ReviewMessageCode.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/review/MemberIdNotExistException.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/review/NotificationIdNotExistException.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/review/ReceiveMemberIdNotExistException.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/review/ReviewContentNotExistException.java
  src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
  src/main/java/com/kakaoseventeen/dogwalking/review/controller/ReviewController.java
  src/main/java/com/kakaoseventeen/dogwalking/review/domain/Review.java
  src/main/java/com/kakaoseventeen/dogwalking/review/dto/ReviewEvalDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/review/dto/WriteReviewReqDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/review/service/ReviewWriteService.java
Labels: develop

#133 비밀번호 길이 검증 로직 수정
  build.gradle
  src/main/java/com/kakaoseventeen/dogwalking/member/service/Validator.java
  src/test/java/com/kakaoseventeen/dogwalking/member/valid/ValidatorTest.java
Labels: bug

#135 회원가입 비밀번호 패턴 정규식 특수문자 추가
  src/main/java/com/kakaoseventeen/dogwalking/member/service/Validator.java
  src/test/java/com/kakaoseventeen/dogwalking/member/valid/ValidatorTest.java
Labels: enhancement

#153 지원서 조회, 작성 기능
  src/main/java/com/kakaoseventeen/dogwalking/application/controller/ApplicationController.java
  src/main/java/com/kakaoseventeen/dogwalking/application/domain/Application.java
  src/main/java/com/kakaoseventeen/dogwalking/application/dto/CreateAppReqDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/application/dto/GetAppResDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationReadService.java
  src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationWriteService.java
  src/main/java/com/kakaoseventeen/dogwalking/match/repository/MatchingRepository.java
Labels: develop

#175 리뷰 500 에러 수정
  src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationReadService.java
  src/main/java/com/kakaoseventeen/dogwalking/match/repository/MatchingRepository.java
  src/main/java/com/kakaoseventeen/dogwalking/notification/domain/Notification.java
  src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
  src/main/java/com/kakaoseventeen/dogwalking/review/service/ReviewWriteService.java
  src/test/java/com/kakaoseventeen/dogwalking/review/service/ReviewWriteServiceTest.java
Labels: bug

#177 채팅목록 조회 기능
  src/main/java/com/kakaoseventeen/dogwalking/chat/controller/ChatRoomController.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatListResDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/repository/ChatMessageRepository.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/repository/ChatRoomRepository.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
  src/main/java/com/kakaoseventeen/dogwalking/match/repository/MatchingRepository.java
  src/main/java/com/kakaoseventeen/dogwalking/match/service/MatchService.java
  src/main/java/com/kakaoseventeen/dogwalking/notification/domain/Notification.java
  src/main/java/com/kakaoseventeen/dogwalking/walk/repository/WalkRepository.java
Labels: develop

#201 채팅방 생성 오류 수정
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GlobalExceptionHandler.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/ChatRoomMessageCode.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatroom/ChatRoomMatchNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatroom/ChatRoomMemberNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/application/controller/ApplicationController.java
  src/main/java/com/kakaoseventeen/dogwalking/application/dto/GetAppResDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationReadService.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/domain/ChatRoom.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatListResDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatRoomReqDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomWriteService.java
  src/main/java/com/kakaoseventeen/dogwalking/review/service/ReviewWriteService.java
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/repository/ChatRoomRepositoryTest.java
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/service/ChatRoomReadServiceTest.java
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/service/ChatRoomWriteServiceTest.java
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/service/ChatRoomWriteServiceUnitTest.java
Labels: bug

#207 리뷰 페이지에 필요한 정보 조회 기능 구현
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GlobalExceptionHandler.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/ReviewMessageCode.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/review/ReviewMemberNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/review/controller/ReviewController.java
  src/main/java/com/kakaoseventeen/dogwalking/review/dto/GetReviewResDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/review/service/ReviewReadService.java
Labels: develop

#209 지원서 추가 요구사항 구현
  src/main/java/com/kakaoseventeen/dogwalking/application/controller/ApplicationController.java
  src/main/java/com/kakaoseventeen/dogwalking/application/dto/CreateAppReqDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationWriteService.java
Labels: bug

#214 채팅 기능 통합 테스트
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/dummyData/PostConstructor.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/controller/ChatController.java
  src/main/java/com/kakaoseventeen/dogwalking/config/WebSocketConfig.java
  src/main/resources/static/css/main.css
  src/main/resources/static/index.html
  src/main/resources/static/js/main.js
Labels: enhancement

#215 Member 제외한 더미 데이터 삭제
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/dummyData/PostConstructor.java
Labels: hotfix

#222 UserProfile에 사용되는 Notification Repository 쿼리 Join절 수정
  src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
  src/main/java/com/kakaoseventeen/dogwalking/walk/controller/WalkController.java
Labels: bug

#227 종료되고, 리뷰가 작성되지 않은 산책 반환 API Spec 추가
  src/main/java/com/kakaoseventeen/dogwalking/review/controller/ReviewController.java
  src/main/java/com/kakaoseventeen/dogwalking/review/service/ReviewWriteService.java
  src/main/java/com/kakaoseventeen/dogwalking/walk/dto/WalkRespDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/walk/repository/WalkRepository.java
  src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
Labels: develop

#228 Allowed Origin Pattern 수정
  src/main/java/com/kakaoseventeen/dogwalking/config/WebSocketConfig.java
Labels: hotfix

#229 채팅기능 matchId추가, 지원서 작성 전 조회 기능
  src/main/java/com/kakaoseventeen/dogwalking/application/controller/ApplicationController.java
  src/main/java/com/kakaoseventeen/dogwalking/application/dto/GetAppMemberResDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationReadService.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatListResDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
  src/main/java/com/kakaoseventeen/dogwalking/review/controller/ReviewController.java
  src/main/java/com/kakaoseventeen/dogwalking/review/service/ReviewReadService.java
Labels: develop

#230 지원서 작성 커스텀 예외
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/ApplicationMessageCode.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/application/ApplicationMemberNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/application/NotificationNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationWriteService.java
Labels: hotfix

#235 채팅 내역 조회
  src/main/java/com/kakaoseventeen/dogwalking/chat/controller/ChatController.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatMessageResDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/repository/ChatMessageRepository.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatMessageReadService.java
Labels: hotfix

#239 배포 파일
  goorm.manifest
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/configs/init.sql
  k8s/kustomization.yaml
  k8s/mariadb.yaml
  k8s/nginx.yaml
Labels: deployment

#246 채팅 목록 조회 분기점 생성
  src/main/java/com/kakaoseventeen/dogwalking/chat/dto/ChatListResDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
Labels: develop, hotfix

#248 채팅 목록 조회 응답 데이터 변경
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
Labels: enhancement

#252 Exception 의존 에러 핸들링
  src/main/java/com/kakaoseventeen/dogwalking/member/controller/MemberController.java
  src/main/java/com/kakaoseventeen/dogwalking/member/service/MemberService.java
Labels: bug

#256 hibernate-diarect 방언 문제 해결
  src/main/resources/application-cloudtype.yml
Labels: bug

#258 테스트 배포 환경 설정
  build.gradle
  goorm.manifest
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/configs/init.sql
  k8s/kustomization.yaml
  k8s/mariadb.yaml
  k8s/nginx.yaml
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/ChatMessageCode.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatMessage/ChatRoomNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatMessageReadService.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatMessageWriteServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/repository/ChatRoomRepositoryTest.java
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/service/ChatRoomWriteServiceUnitTest.java
Labels: bug

#266 커스텀 예외처리
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/ChatMessageCode.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/ChatRoomMessageCode.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GlobalExceptionHandler.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/application/ApplicationMemberNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatMessage/MemberIdNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatroom/ChatMessageNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatroom/InvalidMemberException.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatroom/WalkNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatMessageWriteServiceImpl.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
Labels: enhancement

#268 Member Profile 쿼리 수정
  src/main/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepository.java
Labels: bug

#277 테스트 검수
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatMessage/NotFoundMemberInChatRoomException.java
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatmessage/integration/WebSocketTest.java
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/controller/ChatRoomControllerTest.java
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/controller/ChatRoomTest.java
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/repository/ChatRoomRepositoryTest.java
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/service/ChatRoomReadServiceTest.java
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/service/ChatRoomWriteServiceTest.java
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/service/ChatRoomWriteServiceUnitTest.java
  src/test/java/com/kakaoseventeen/dogwalking/dog/DogControllerTest.java
  src/test/java/com/kakaoseventeen/dogwalking/dog/DogServiceTest.java
  src/test/java/com/kakaoseventeen/dogwalking/match/controller/MatchControllerTest.java
  src/test/java/com/kakaoseventeen/dogwalking/member/MemberControllerTest.java
  src/test/java/com/kakaoseventeen/dogwalking/member/valid/ValidatorTest.java
  src/test/java/com/kakaoseventeen/dogwalking/notification/controller/HomeControllerTest.java
  src/test/java/com/kakaoseventeen/dogwalking/notification/controller/NotificationControllerTest.java
  src/test/java/com/kakaoseventeen/dogwalking/notification/repository/NotificationJpaRepositoryTest.java
  src/test/java/com/kakaoseventeen/dogwalking/payment/PaymentControllerTest.java
  src/test/java/com/kakaoseventeen/dogwalking/payment/PaymentRespTest.java
  src/test/java/com/kakaoseventeen/dogwalking/review/service/ReviewWriteServiceTest.java
  src/test/java/com/kakaoseventeen/dogwalking/walk/WalkRespTest.java
  src/test/java/com/kakaoseventeen/dogwalking/walk/WalkRestControllerTest.java
  src/test/java/com/kakaoseventeen/dogwalking/walk/WalkServiceTest.java
  src/test/java/com/kakaoseventeen/dogwalking/walkRoad/WalkRoadControllerTest.java
  src/test/java/com/kakaoseventeen/dogwalking/walkRoad/WalkRoadRepsTest.java
  src/test/java/com/kakaoseventeen/dogwalking/walkRoad/WalkRoadServiceTest.java
Labels: enhancement

#279 Dog Profile 수정시 중복되어서 저장되는 문제
  src/main/java/com/kakaoseventeen/dogwalking/dog/domain/Dog.java
  src/main/java/com/kakaoseventeen/dogwalking/member/domain/Member.java
Labels: bug

#280 채팅방 생성 버그수정
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/ApplicationMessageCode.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/ChatMessageCode.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/GlobalExceptionHandler.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/application/ApplicationNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/application/MatchNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/application/service/ApplicationReadService.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/domain/ChatRoom.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/dto/MessageTypeDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatMessageWriteServiceImpl.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomWriteService.java
  src/main/java/com/kakaoseventeen/dogwalking/match/domain/Match.java
Labels: bug, hotfix

#281 환결설정 수정
  src/main/resources/application-cloud.yml
Labels: bug

#285 채팅방 목록조회 버그 픽스
  src/main/java/com/kakaoseventeen/dogwalking/chat/repository/ChatRoomRepository.java
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
  src/main/resources/application-cloud.yml
Labels: bug

#289 채팅방 목록 조회 버그 픽스
  src/main/java/com/kakaoseventeen/dogwalking/chat/service/ChatRoomReadService.java
Labels: bug

#297 미사용 import 삭제
  src/main/java/com/kakaoseventeen/dogwalking/_core/security/RestTemplateConfig.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/dummyData/PostConstructor.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatMessage/NotFoundMemberInChatRoomException.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatroom/ChatMessageNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/application/repository/ApplicationRepository.java
Labels: hotfix

#299 Weekly to develop
  src/main/java/com/kakaoseventeen/dogwalking/_core/security/RestTemplateConfig.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/dummyData/PostConstructor.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatMessage/NotFoundMemberInChatRoomException.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatroom/ChatMessageNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/application/repository/ApplicationRepository.java
  src/main/java/com/kakaoseventeen/dogwalking/walk/dto/WalkResDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/controller/ChatRoomControllerTest.java
  src/test/java/com/kakaoseventeen/dogwalking/notification/controller/HomeControllerTest.java
Labels: hotfix

#300 Develop to master
  src/main/java/com/kakaoseventeen/dogwalking/_core/security/RestTemplateConfig.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/dummyData/PostConstructor.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatMessage/NotFoundMemberInChatRoomException.java
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/exception/chatroom/ChatMessageNotFoundException.java
  src/main/java/com/kakaoseventeen/dogwalking/application/repository/ApplicationRepository.java
  src/main/java/com/kakaoseventeen/dogwalking/walk/dto/WalkResDTO.java
  src/main/java/com/kakaoseventeen/dogwalking/walk/service/WalkService.java
  src/test/java/com/kakaoseventeen/dogwalking/chat/chatroom/controller/ChatRoomControllerTest.java
  src/test/java/com/kakaoseventeen/dogwalking/notification/controller/HomeControllerTest.java
Labels: hotfix

#306 견주가 리뷰 작성시 리뷰 True 등록
  src/main/java/com/kakaoseventeen/dogwalking/review/controller/ReviewController.java
  src/main/java/com/kakaoseventeen/dogwalking/review/service/ReviewWriteService.java
Labels: hotfix

#309 배포환경 적용
  Dockerfile
  build.gradle
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/configs/init.sql
  k8s/frontend.yaml
  k8s/kustomization.yaml
  k8s/mysql.yaml
  k8s/nginx.yaml
  src/main/java/com/kakaoseventeen/dogwalking/_core/utils/S3Config.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: deployment
